name: Build and test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
 
jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore

    - name: Test
      run: dotnet test src --no-build --verbosity normal --logger "trx;LogFileName=test_results.trx"

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: ${{ github.workspace }}/**/TestResults/**/*.trx
